### ISSUE TITLE
プロジェクトのピックアップに載せる記事にタグをつける

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/Ghost-Theme-2020#43]
タグ: `#pickups-projects`
とりあえず5件

blocks #7

**Comment by cskd8** [comment]
3件しか表示されないので3件選ぼうとしたのですが、今年のプロジェクトはすでに選ばれていたものだけでした。PKにpickups-projectsを追加したのですが、3件は変わらなかったのでこれで良いと思います。
