### ISSUE TITLE
特定のスクロール位置でヘッダーの高さが振動する

### ISSUE THREAD

**Issue by yto60** [traPtitech/Ghost-Theme-2020#49]
![screenshot](https://user-images.githubusercontent.com/28436261/77694590-9cfd4e00-6fed-11ea-884f-f9f0a281bbca.gif)

`class="thin"` がついたり消えたりしているので、 [ここ](https://github.com/traPtitech/Ghost-Theme-2020/blob/master/assets/js/header-thin-toggle.js#L13) の条件を修正すれば良さそう？

**Comment by sapphi-red** [comment]
https://twitter.com/kmgk0215/status/1243395939026362369

**Comment by sapphi-red** [comment]
つけるときの位置と、外すときの位置を、つけるときのほうが下になるようにするとたぶん…？
